pull_request_rules:
  - name: backport-on-bp
    conditions:
      - label = bp
    actions:
      backport:
        branches:
          - stable
        ignore_conflicts: true

  - name: copy-on-cp
    conditions:
      - label = cp
    actions:
      copy:
        branches:
          - stable
        ignore_conflicts: true

  - name: squash-on-sq
    conditions:
      - label = sq
    actions:
      squash:

  - name: update-on-up
    conditions:
      - label = up
    actions:
      update:

  - name: rebase-on-rb
    conditions:
      - label = rb
    actions:
      rebase:

  - name: delete-head-on-close
    conditions:
      - closed
    actions:
      delete_head_branch:
        force: true
